import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = !!cookies().get('token')

  return (
    <html lang="en">
      <body className={inter.className}>
        {token && <Link href={'/'}>Home</Link>}
        {children}
      </body>
    </html>
  );
}
